### ISSUE TITLE
socket.error: [Errno 107] Transport endpoint is not connected (Gentoo)

### ISSUE THREAD

**Issue by dtony** [chrippa/ds4drv#22]
I got this error when trying to run ps4drv on Gentoo.  The entire trace is : 

```
ds4drv
[info][controller 1] Created devices /dev/input/js2 (joystick) /dev/input/event10 (evdev) 
[info][bluetooth] Scanning for devices
[info][bluetooth] Found device A4:15:66:6F:3B:A0
Traceback (most recent call last):
  File "/usr/bin/ds4drv", line 9, in <module>
    load_entry_point('ds4drv==0.3.0', 'console_scripts', 'ds4drv')()
  File "/usr/lib64/python2.7/site-packages/ds4drv/__main__.py", line 325, in main
    for device in backend.devices:
  File "/usr/lib64/python2.7/site-packages/ds4drv/backends/bluetooth.py", line 117, in devices
    device = self.find_device()
  File "/usr/lib64/python2.7/site-packages/ds4drv/backends/bluetooth.py", line 106, in find_device
    return BluetoothDS4Device.connect(bdaddr)
  File "/usr/lib64/python2.7/site-packages/ds4drv/backends/bluetooth.py", line 34, in connect
    return cls(addr, ctl_socket, int_socket)
  File "/usr/lib64/python2.7/site-packages/ds4drv/backends/bluetooth.py", line 41, in __init__
    super(BluetoothDS4Device, self).__init__(addr, "bluetooth")
  File "/usr/lib64/python2.7/site-packages/ds4drv/device.py", line 70, in __init__
    self.set_operational()
  File "/usr/lib64/python2.7/site-packages/ds4drv/backends/bluetooth.py", line 66, in set_operational
    self.set_led(255, 255, 255)
  File "/usr/lib64/python2.7/site-packages/ds4drv/device.py", line 82, in set_led
    self._control()
  File "/usr/lib64/python2.7/site-packages/ds4drv/device.py", line 75, in _control
    flash_led2=self._led_flash[1], **kwargs)
  File "/usr/lib64/python2.7/site-packages/ds4drv/device.py", line 130, in control
    self.write_report(report_id, pkt)
  File "/usr/lib64/python2.7/site-packages/ds4drv/backends/bluetooth.py", line 63, in write_report
    self.ctl_sock.sendall(hid + data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 107] Transport endpoint is not connected
```

bluez version is 4.101

**Comment by bakkerthehacker** [comment]
I also have this issue.  Following the instructions [here](http://blog.petrockblock.com/forums/topic/tutorial-retropie-with-dualshock-4-and-bluetooth/#post-82447) i got it work on Linux Mint 17 using the command

`bluez-simple-agent hci0 <my ds4 mac> remove`

it prints out `Creating device failed: org.bluez.Error.ConnectionAttemptFailed: Page Timeout` but it still works

**Comment by Ape** [comment]
Suddenly this problem started to occur for me. I fixed this with bluetoothctl and "remove MAC".

**Comment by aloehart** [comment]
To add, on a raspberry pi it worked fine until I added a line to rc.local to run it silently at boot. Even after removing the single line from the script, this issue is still persisting. 

The pi is running a modified version of debian with all the core functions of the OS in tact.  

Here's the output 

>pi@raspisan ~ $ sudo ds4drv
>[info][controller 1] Created devices /dev/input/js0 (joystick) /dev/input/event1 (evdev)
>[info][bluetooth] Scanning for devices
>[info][bluetooth] Found device AC:FD:93:01:89:03
>[error][bluetooth] Unable to connect to detected device: Failed to set operational mode: [Errno 107] >Transport endpoint is not connected
>[info][bluetooth] Scanning for devices
>[info][bluetooth] Found device AC:FD:93:01:89:03
>[error][bluetooth] Unable to connect to detected device: Failed to set operational mode: [Errno 107] >Transport endpoint is not connected
>[info][bluetooth] Scanning for devices  

It loops at that point for as long as the controller is in pair mode. The above was on a single pairing attempt.

**Comment by Forsok** [comment]
I had the same problem, after i paired the controller with my PS4.
`bluez-test-device remove xx:xx:xx:xx:xx:xx`
worked for me.

**Comment by Ape** [comment]
If the bluetoothctl trick doesn't work, make sure that you have bluetooth.service running on systemd (if you are using systemd).

**Comment by apryamostanov** [comment]
Forsok, many thanks.
PS4 controller has some issue.
bluez-test-device remove xx:xx:xx:xx:xx:xx
helped.

**Comment by rodrigo-ceccato** [comment]
Any updates? Having the same issue on Fedora 32 (Tranposrt endpoint is not connected)

**Comment by maxie7** [comment]
bluez-test-device remove xx:xx:xx:xx:xx:xx doesn't help;
With sudo apt-cache search bluez-test  i found and installed bluez-test-scripts && bluez-test-tools, but I have the same result
'command not found'...

> sudo ds4drv
> [info][controller 1] Created devices /dev/input/js0 (joystick) /dev/input/event15 (evdev) 
> [info][bluetooth] Scanning for devices
> [info][bluetooth] Found device A4:53:85:A6:17:E6
> [error][bluetooth] Unable to connect to detected device: Failed to set operational mode: [Errno 107] Transport endpoint is not connected
> [info][bluetooth] Scanning for devices
> [info][bluetooth] Found device A4:53:85:A6:17:E6

**Comment by maxie7** [comment]
I've read a lot of docs && I suppose that it's due to bluetooth dongle... It has bluetooth 2.1

**Comment by rodrigo-ceccato** [comment]
Yep... I upgraded my bluetooth dongle (it was from 2007) yesterday, and now everything works fine...
